### PR TITLE
added karpenter - k8s v1.32 compatibility

### PR DESCRIPTION
**Pull request by edgarfzo**
*Feat:*
- added v 1.32 k8s compatibility to karpenter addon

*Description of changes:*
- added an extra line to map minimumm version for k8s 1.32

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: lib/addons/karpenter/index.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ import { KarpenterControllerPolicy, KarpenterControllerPolicyBeta } from './iam'
 
 class versionMap {
     private static readonly versionMap: Map<string, string> = new Map([
+        [KubernetesVersion.V1_32.version, '0.37.5'],
```
Comment (shapirov103) [inline lib/addons/karpenter/index.ts:19]: The compatibility matrix states 1.2.x for 1.32. Since the default is moved to 1.1.2 , why not reflect consistent versions in the map, e.g. 1.2.1 for 1.32 and 1.05 for 1.31?

File: lib/addons/karpenter/index.ts [hunk 2]
```diff
@@ -301,7 +302,7 @@ const RELEASE = 'blueprints-addon-karpenter';
 const defaultProps: HelmAddOnProps = {
     name: KARPENTER,
     namespace: "kube-system",
-    version: '1.0.6',
+    version: '1.1.2',
```
Comment (shapirov103) [inline lib/addons/karpenter/index.ts:305]: why this version  specifically?

**Review by shapirov103 — COMMENTED** [review]
@edgarfzo thank you for your contribution! 
I left a couple of questions, I will need to run e2e tests after I understand your reasoning.

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts:19]: That is a good point

File: lib/addons/karpenter/index.ts (hunk 2 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts:305]: Because v 1.1.2 works with k8s 1.32 as reported
https://github.com/aws/karpenter-provider-aws/issues/7629

Comment (shapirov103) [reply lib/addons/karpenter/index.ts:305]: According to the [compatibility matrix](https://karpenter.sh/docs/upgrading/compatibility/) the version for 1.32 should be 1.2.1, hence I asked.

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts:19]: Done :)

File: lib/addons/karpenter/index.ts (hunk 2 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts]: Done :)

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (shapirov103) [reply lib/addons/karpenter/index.ts:19]: I don't see the applied change as per comment, 1.32 still has 0.37.5 as the target version. Not planning to apply these changes? It is a quick change, however, to change it for me now means applying a push to your fork.

**Review by shapirov103 — COMMENTED** [review]
@edgarfzo the github action failed with 

```
Error: lib/addons/karpenter/index.ts(19,28): error TS2551: Property 'V1_32' does not exist on type 'typeof KubernetesVersion'. Did you mean 'V1_20'?
make[1]: *** [Makefile:24: compile] Error 2
make[1]: Leaving directory '/home/runner/work/cdk-eks-blueprints/cdk-eks-blueprints'
make: *** [Makefile:21: build] Error 2
Error: Process completed with exit code 2.
```

I checked and in the latest CDK 2.178 there is no 1.32 support. Have you tested this change?

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts:19]: You are right, now it is changed

**Comment by edgarfzo** [comment]
> @edgarfzo the github action failed with
> 
> ```
> Error: lib/addons/karpenter/index.ts(19,28): error TS2551: Property 'V1_32' does not exist on type 'typeof KubernetesVersion'. Did you mean 'V1_20'?
> make[1]: *** [Makefile:24: compile] Error 2
> make[1]: Leaving directory '/home/runner/work/cdk-eks-blueprints/cdk-eks-blueprints'
> make: *** [Makefile:21: build] Error 2
> Error: Process completed with exit code 2.
> ```
> 
> I checked and in the latest CDK 2.178 there is no 1.32 support. Have you tested this change?

You are right, aws-cdk is about to release this change
https://github.com/aws/aws-cdk/pulls?q=is%3Apr+1.32+is%3Aclosed

Let's wait to approve with the new aws cdk version

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (shapirov103) [reply lib/addons/karpenter/index.ts:19]: Please check again, the change did not make into the PR.

**Comment by paulchambers** [comment]
Is this still being worked on? aws-cdk has support for 1.32 since [v2.179.0](https://github.com/aws/aws-cdk/releases/tag/v2.179.0)

**Comment by vumdao** [comment]
@edgarfzo  Can you please update cdk version to `2.186.0` ?

**Comment by edgarfzo** [comment]
> @edgarfzo Can you please update cdk version to `2.186.0` ?

Done

**Comment by edgarfzo** [comment]
> Is this still being worked on? aws-cdk has support for 1.32 since [v2.179.0](https://github.com/aws/aws-cdk/releases/tag/v2.179.0)
> 
> Note moving to version 1.1 or higher of karpenter will need further changes in the addon as support for the beta CRDs is removed in that version https://karpenter.sh/v1.3/upgrading/upgrade-guide/

Done

File: lib/addons/karpenter/index.ts (hunk 1 above)
Comment (edgarfzo) [reply lib/addons/karpenter/index.ts]: Done

**Comment by shapirov103** [comment]
@edgarfzo it fails basic build test. You can reproduce by running `make build` on your fork. The `aws-cdk` version has diverged, it is 2.1007.0  - not 2.186.

**Review by shapirov103 — COMMENTED** [review]
Lib is on 2.187 and such version, cdk executable is now following a separate release and is on 2.1007.0. Please test by running `npm i` on the branch. The main branch has been already updated with these dependencies:
```
  "peerDependencies": {
    "aws-cdk": "2.1007.0",
    "aws-cdk-lib": "2.187.0"
  }
```

**Review by shapirov103 — APPROVED** [review]
LGTM
