### ISSUE TITLE
[eks-blueprints-cluster]: Type 'ICluster' is missing the following properties from type 'Cluster': role, adminRole, _fargateProfiles, _clusterResource, and 28 more.

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#766]
### Describe the bug

I got following error when upgrade blueprints to v1.10.0
```
TSError: ⨯ Unable to compile TypeScript:
src/eks-blueprints/eks-cluster-stacks.ts:41:5 - error TS2740: Type 'ICluster' is missing the following properties from type 'Cluster': role, adminRole, _fargateProfiles, _clusterResource, and 28 more.
```

It works well with following versions
cdk: v2.87.0
blueprints: v1.8.0

### Expected Behavior

No error

### Current Behavior

Error 

### Reproduction Steps

```
    const cluster = EksBlueprint.builder()
      .name(eksName)
      .account(reg.account)
      .region(reg.region)
      .addOns(...AddOns)
      .version(EKS_KUBERNETES_VERSION)
      .teams(PlatformAdmin)
      .clusterProvider(EksComponents(reg))
      .build(scope, `${eksName}-eks-blueprint`, {
        description: 'EKS Blueprints',
        env: {
          region: reg.region,
          account: reg.account,
        },
        tags: TagsProp('eks-blueprints', reg),
      });

    this.eksCluster = cluster.getClusterInfo().cluster;
```

### CDK CLI Version

2.87.0

### EKS Blueprints Version

1.10.0

### Node.js Version

v18.16.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4.1

**Comment by shapirov103** [comment]
@vumdao after we implemented import cluster provider, the type is not guaranteed to be `eks.Cluster`. However, if you are provisioning clusters (not importing) then you can just apply an explicit cast:

```typescript
const cluster: eks.Cluster  = b.getClusterInfo().cluster as eks.Cluster;
```

Also, if you don't mind, please share why do you need access to the cluster after provisioning is complete? We will consider extending blueprint to make such cases more native experience.

**Comment by vumdao** [comment]
@shapirov103 I need to get EKS SG, VPC, and openIdConnectProviderIssuer from the EKS cluster to create other resources

**Comment by shapirov103** [comment]
@vumdao thank you for sharing. How do you use openIdConnectProviderIssuer and other attributes?

**Comment by vumdao** [comment]
@shapirov103 
My platform includes Aurora RDS, Apache Airflow and others, they need to communicate with EKS Pods in private network so I need to input EKS SG and VPC in their stacks.

openIdConnectProviderIssuer is used as IAM condition policy when creating IAM role for service account, eg.
```
    const StringLike = new CfnJson(this, 'AirflowWorkerCondiftionJson', {
      value: {
        [`${props.iamOidcIssuer}:sub`]: [
          `system:serviceaccount:kube-system:${AIRFLOW_WORKER_SA}`,
        ],
        [`${props.iamOidcIssuer}:aud`]: 'sts.amazonaws.com',
      },
    });
```

**Comment by shapirov103** [comment]
@vumdao it is more or less clear with EKS SG and VPC, however for SG I encourage you to take a look at [Security Groups for Pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) if you are not using them already. 

As far as IRSA support for service accounts - you can create IRSA service accounts with the blueprints directly. 
Here is an example of a team that is configured with IRSA to access ECR from pods: https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/teams/team-scan/index.ts#L12 

Blueprints handle trust relationship with OIDC provider.  You can use teams or custom addons to provision IRSA accounts.

**Comment by vumdao** [comment]
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/764#issuecomment-1638882161
```
const eksCluster = (b.getClusterInfo().cluster as any) as eks.Cluster;
```
